### ISSUE TITLE
Wrong URL in setup.py

### ISSUE THREAD

**Issue by cmbruns** [latte10am/pyVulkan#4]
Your setup.py has its URL set to "http://pyopengl.sourceforge.net"

But shouldn't this say instead "https://github.com/latte10am/pyVulkan" ?

I noticed because the URL is displayed prominently at https://pypi.python.org/pypi/pyVulkan/0.5

Or is this pyVulkan really a component of pyOpenGL now?

**Comment by latte10am** [comment]
It's just because I copied pyOpenGL's setup script and didn't modify it by mistake. Thank you for reporting.
