### ISSUE TITLE
Add cffi API level to increase performance

### ISSUE THREAD

**Issue by js78** [latte10am/pyVulkan#8]
Currently you use cffi at the ABI level, it could be great for performance to use it at the API level.
See : https://cffi.readthedocs.io/en/latest/overview.html

**Comment by latte10am** [comment]
AFAIK, API level is useful when you have some C source code to be compiled to .so. But pyVulkan is just a binding for exising C API of vulkan, so I'm not sure about the potential performance improvements.

**Comment by js78** [comment]
Indeed you seems right but I don't know enough CFFI.
